version: "3"
services:
  hub:
    image: selenium/hub:3.14
    # ports:
    #   - "4444:4444"                 port mapping is ok for local 
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module1:
    image: dgdocker1987/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=search-module.xml
    volumes:
      - ./output/search-result-firefox:/usr/share/udemy/test-output
  search-module2:
    image: dgdocker1987/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=search-module.xml
    volumes:
      - ./output/search-result-chrome:/usr/share/udemy/test-output    

  